repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
- repo: https://github.com/aleksandr-vin/texcret
  rev: 0.2.0
  hooks:
  - id: texcret
    args: ["--origin", "https://aleksandr.vin"]
  - id: texcret-check-markers
