repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
- repo: https://github.com/aleksandr-vin/texcret
  rev: 0.2.0
  hooks:
  - id: texcret
    entry: env PINENTRY=pinentry-mac texcret texcret --in-file --force-secrets --no-arg-passwords --password -
    args: ["--origin", "https://aleksandr.vin"]
  - id: texcret-check-markers
